import { describe, expect, it } from "vitest";
import { computeAnalytics, sessionsToCsv } from "@/lib/admin/analytics";
import { sessionSchema, type Session, type SessionStatus } from "@/lib/schema";

const BASE_TIME = Date.UTC(2026, 0, 15, 10, 0, 0);

function session(overrides: Partial<Session> = {}): Session {
  return sessionSchema.parse({
    id: Math.random().toString(36).slice(2),
    shortId: Math.random().toString(36).slice(2, 10),
    presetId: "preset-1",
    consent: { accepted: true, version: "1.0", text: "…", acceptedAt: BASE_TIME },
    choices: { sceneId: null, poseId: null, treatmentId: null },
    status: "started" satisfies SessionStatus,
    createdAt: BASE_TIME,
    ...overrides,
  });
}

describe("funnel", () => {
  it("is monotonic — each stage is at least as large as the next", () => {
    const analytics = computeAnalytics(
      [
        session(),
        session({ sourceUrl: "https://example.com/a.jpg", status: "capturing" }),
        session({
          sourceUrl: "https://example.com/b.jpg",
          variantUrls: ["https://example.com/v1.jpg"],
          status: "ready",
        }),
        session({
          sourceUrl: "https://example.com/c.jpg",
          finalUrl: "https://example.com/f.jpg",
          status: "completed",
        }),
      ],
      0.15,
    );

    const counts = analytics.funnel.map((stage) => stage.count);
    expect(counts).toEqual([4, 3, 2, 1]);
  });

  it("keeps a purged session in the funnel even though its URLs are gone", () => {
    // Regression: reading stage from stored URLs made a purged-but-completed
    // session count as completed while appearing to skip every earlier stage.
    const purged = session({
      status: "completed",
      fields: {},
      sourceUrl: null,
      variantUrls: [],
      finalUrl: null,
      purgedAt: BASE_TIME + 1000,
      timings: {
        startedAt: BASE_TIME,
        capturedAt: BASE_TIME + 10_000,
        generateStartedAt: BASE_TIME + 12_000,
        generateEndedAt: BASE_TIME + 30_000,
        completedAt: BASE_TIME + 35_000,
      },
    });

    const counts = computeAnalytics([purged], 0.15).funnel.map((stage) => stage.count);
    expect(counts).toEqual([1, 1, 1, 1]);
  });

  it("counts a failed generation as reaching the photo, not the image", () => {
    const failed = session({
      status: "failed",
      sourceUrl: "https://example.com/a.jpg",
      timings: {
        startedAt: BASE_TIME,
        capturedAt: BASE_TIME + 8_000,
        generateStartedAt: BASE_TIME + 9_000,
        generateEndedAt: BASE_TIME + 20_000,
        completedAt: null,
      },
    });

    const counts = computeAnalytics([failed], 0.15).funnel.map((stage) => stage.count);
    expect(counts).toEqual([1, 1, 0, 0]);
  });
});

describe("spend", () => {
  it("still counts images generated by a session whose data was purged", () => {
    const analytics = computeAnalytics(
      [
        session({ imagesGenerated: 2, status: "completed" }),
        session({ imagesGenerated: 4, status: "completed", purgedAt: BASE_TIME, finalUrl: null }),
      ],
      0.15,
    );

    expect(analytics.estimatedSpendUsd).toBeCloseTo(0.9, 2);
  });

  it("charges the 4K rate when the preset asks for it", () => {
    expect(computeAnalytics([session({ imagesGenerated: 2 })], 0.3).estimatedSpendUsd).toBeCloseTo(
      0.6,
      2,
    );
  });
});

describe("timings", () => {
  it("uses the median so one stuck request cannot distort the headline", () => {
    const withGeneration = (ms: number) =>
      session({
        timings: {
          startedAt: BASE_TIME,
          capturedAt: null,
          generateStartedAt: BASE_TIME,
          generateEndedAt: BASE_TIME + ms,
          completedAt: null,
        },
      });

    const analytics = computeAnalytics(
      [withGeneration(18_000), withGeneration(20_000), withGeneration(600_000)],
      0.15,
    );

    expect(analytics.medianGenerationMs).toBe(20_000);
  });
});

describe("csv export", () => {
  it("neutralises values that a spreadsheet would execute as a formula", () => {
    const csv = sessionsToCsv(
      [session({ fields: { name: "=1+1", email: "guest@example.com" } })],
      ["name", "email"],
    );

    const row = csv.split("\n")[1];
    expect(row).toContain(`"'=1+1"`);
    expect(row).not.toContain(`"=1+1"`);
  });

  it("escapes embedded quotes rather than breaking the row", () => {
    const csv = sessionsToCsv([session({ fields: { name: 'Ali "Bo" Chen' } })], ["name"]);
    expect(csv.split("\n")[1]).toContain(`"Ali ""Bo"" Chen"`);
  });

  it("names its columns from the fields actually collected", () => {
    const csv = sessionsToCsv([session({ fields: { name: "A", company: "B" } })], [
      "name",
      "company",
    ]);
    expect(csv.split("\n")[0]).toContain(`"company"`);
  });
});
